# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'magnetSensorGui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(890, 387)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_ID = QtWidgets.QLabel(self.centralwidget)
        self.label_ID.setGeometry(QtCore.QRect(70, 30, 241, 101))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_ID.setFont(font)
        self.label_ID.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_ID.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_ID.setLineWidth(3)
        self.label_ID.setMidLineWidth(2)
        self.label_ID.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ID.setObjectName("label_ID")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(70, 160, 241, 111))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.comboBox_Port = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox_Port.setGeometry(QtCore.QRect(10, 30, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_Port.setFont(font)
        self.comboBox_Port.setObjectName("comboBox_Port")
        self.pushButton_Refresh = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_Refresh.setGeometry(QtCore.QRect(10, 70, 90, 30))
        self.pushButton_Refresh.setStyleSheet("            QPushButton {\n"
"                border: 2px solid green;\n"
"                border-radius: 5px;\n"
"                background-color: white;\n"
"                padding: 5px;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: lightgray;\n"
"            }\n"
"            QPushButton:pressed {\n"
"                background-color: darkgray;\n"
"            }")
        self.pushButton_Refresh.setObjectName("pushButton_Refresh")
        self.pushButton_Start = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_Start.setGeometry(QtCore.QRect(130, 70, 90, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_Start.setFont(font)
        self.pushButton_Start.setStyleSheet("            QPushButton {\n"
"                border: 2px solid green;\n"
"                border-radius: 5px;\n"
"                background-color: white;\n"
"                padding: 5px;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: lightgray;\n"
"            }\n"
"            QPushButton:pressed {\n"
"                background-color: darkgray;\n"
"            }")
        self.pushButton_Start.setAutoDefault(False)
        self.pushButton_Start.setDefault(False)
        self.pushButton_Start.setFlat(False)
        self.pushButton_Start.setObjectName("pushButton_Start")
        self.plotWidget_RightTop = PlotWidget(self.centralwidget)
        self.plotWidget_RightTop.setGeometry(QtCore.QRect(330, 30, 481, 241))
        self.plotWidget_RightTop.setObjectName("plotWidget_RightTop")
        self.horizontalSlider_Plot = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_Plot.setGeometry(QtCore.QRect(339, 280, 471, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.horizontalSlider_Plot.setFont(font)
        self.horizontalSlider_Plot.setStyleSheet("")
        self.horizontalSlider_Plot.setMinimum(10)
        self.horizontalSlider_Plot.setMaximum(500)
        self.horizontalSlider_Plot.setPageStep(10)
        self.horizontalSlider_Plot.setProperty("value", 100)
        self.horizontalSlider_Plot.setSliderPosition(100)
        self.horizontalSlider_Plot.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_Plot.setObjectName("horizontalSlider_Plot")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 890, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "3-axis magnetic sensor"))
        self.label_ID.setText(_translate("MainWindow", "No Magnet"))
        self.groupBox_4.setTitle(_translate("MainWindow", "COMMs Port"))
        self.pushButton_Refresh.setText(_translate("MainWindow", "Refresh"))
        self.pushButton_Start.setText(_translate("MainWindow", "Start"))
from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
